djangonautic/accounts/urls.py
from django.urls import path
# importing Views that'll be referenced from views.py
from . import views

# want to namespace our urls so that the names given to them here can be repeated in other apps without confusion when we need to use them in templates

app_name = 'accounts'

urlpatterns = [
    # parameters are 1. the route string,  2. the view handling the route, and 3. the name for the given URL
    # pre-appended with /accounts/ in base app urls.py
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

djangonautic/articles/urls.py
from django.urls import path
# importing Views that'll be referenced from views.py
from . import views

# want to namespace our urls so that the names given to them here can be repeated in other apps without confusion when we need to use them in templates

app_name = 'articles'
# Remember: Django runs through urls in order until it hits a match, so you want the most general route i.e. the '' route for the homepage, to be last
urlpatterns = [
    # parameters are 1. the route string,  2. the view handling the route, and 3. the name for the given URL
    # will be pre-appended with articles/ based on specification in root app's urls.py (see djangonautic/urls.py)
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail")
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path
# use include to add urls from other applications
from django.urls import include
# importing Views that'll be referenced from views.py
from . import views
# for working with static files in local development, NEVER PRODUCTION!
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# for working with uploading media
from django.conf.urls.static import static
# importing properties in the settings.py file
from django.conf import settings
# want to have access to views from articles app
from articles import views as article_views

# Remember: Django runs through urls in order until it hits a match, so you want the most general route i.e. the '' route for the homepage, to be last
urlpatterns = [
    path(route= 'admin/', view= admin.site.urls),
    # parameters are 1. the route string and 2. the view handling the route
    path(route= 'about/', view= views.about),
    # any urls defined in articles app will be pre-appended with articles/
    path(route= 'articles/', view= include('articles.urls', namespace='aricles')),
    # any urls defined in accounts app will be pre-appended with accounts/
    path(route= 'accounts/', view= include('accounts.urls', namespace='accounts')),
    # '' for the homepage
    path(route= '', view= article_views.article_list, name="home")
]

# url for static files
# function will first check to see that we are in debug mode (should only be true in development) then append itself
urlpatterns += staticfiles_urlpatterns()

# url for uploading media
# static funtion takes as arguments 1. prefix string for the url route and 2. document_root which is where uploaded media will go
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>About Us</h1>
        <p>We Like Django</p>
    </body>
</html>

djangonautic/templates/base_layout.html
<!-- using this static module as opposed to hardcoding the link to static files as they may change location over time-->
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="wrapper">
            <header>
                <!-- using template tag to get url based on the name parameter assigned when creating the urls -->
                <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="Image for link to articles list"></a></h1>
                <nav>
                    <ul>
                    <!-- user object is available to all templates -->
                    {% if user.is_authenticated %}
                        <li>
                            <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
                                {% csrf_token %}
                                <button type="submit" name="logout_button">Logout</button>
                            </form>
                        </li>
                        <li><a href="{% url 'articles:create' %}" class= 'highlight'>Create New Article</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                    </ul>
                </nav>
            </header>
            {% block content%}
            {% endblock %}
        </div>
    </body>
</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Homepages</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome to Djangonautic</p>
    </body>
</html>