djangonautic/accounts/urls.py
from django.urls import path
# importing Views that'll be referenced from views.py
from . import views

# want to namespace our urls so that the names given to them here can be repeated in other apps without confusion when we need to use them in templates

app_name = 'accounts'

urlpatterns = [
    # parameters are 1. the route string,  2. the view handling the route, and 3. the name for the given URL
    # pre-appended with /accounts/ in base app urls.py
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

djangonautic/articles/urls.py
from django.urls import path
# importing Views that'll be referenced from views.py
from . import views

# want to namespace our urls so that the names given to them here can be repeated in other apps without confusion when we need to use them in templates

app_name = 'articles'
# Remember: Django runs through urls in order until it hits a match, so you want the most general route i.e. the '' route for the homepage, to be last
urlpatterns = [
    # parameters are 1. the route string,  2. the view handling the route, and 3. the name for the given URL
    # will be pre-appended with articles/ based on specification in root app's urls.py (see djangonautic/urls.py)
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail")
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path
# use include to add urls from other applications
from django.urls import include
# importing Views that'll be referenced from views.py
from . import views
# for working with static files in local development, NEVER PRODUCTION!
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# for working with uploading media
from django.conf.urls.static import static
# importing properties in the settings.py file
from django.conf import settings
# want to have access to views from articles app
from articles import views as article_views

# Remember: Django runs through urls in order until it hits a match, so you want the most general route i.e. the '' route for the homepage, to be last
urlpatterns = [
    path(route= 'admin/', view= admin.site.urls),
    # parameters are 1. the route string and 2. the view handling the route
    path(route= 'about/', view= views.about),
    # any urls defined in articles app will be pre-appended with articles/
    path(route= 'articles/', view= include('articles.urls', namespace='aricles')),
    # any urls defined in accounts app will be pre-appended with accounts/
    path(route= 'accounts/', view= include('accounts.urls', namespace='accounts')),
    # '' for the homepage
    path(route= '', view= article_views.article_list, name="home")
]

# url for static files
# function will first check to see that we are in debug mode (should only be true in development) then append itself
urlpatterns += staticfiles_urlpatterns()

# url for uploading media
# static funtion takes as arguments 1. prefix string for the url route and 2. document_root which is where uploaded media will go
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/articles/models.py
from django.db import models
# for snippet function
import re, string
# importing User model for author
from django.contrib.auth.models import User

# Create your models here.
# extends the Django models.Model class
class Article(models.Model):
    # see documentation for all of the different field types supported
    title = models.CharField(max_length=100)
    # the part of a URL that identifies a page in human-readable keywords is sometimes refered to as the slug (Wikipedia)
    slug = models.SlugField()
    body = models.TextField()
    # auto_now_a=True automatically sets the field to "now" when the object is first created
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    # author is link to user who created article
    # if the author it references is deleted, set the author to the default which is None
    author= models.ForeignKey(to= User, on_delete= models.SET_DEFAULT, default= None)

    # string representation
    def __str__(self):
        return self.title

    # function to return a shorter snippet of the larger article
    def snippet(self):
        # help from https://stackoverflow.com/questions/9797357/dividing-a-string-at-various-punctuation-marks-using-split
        # grabing first sentence of a body plus "..."
        return (re.split('[!.?]', self.body)[0] + '...')

djangonautic/articles/forms.py
# import forms module
from django import forms
# import our own models
from . import models

# class for article creation which extends the ModelForm class
class CreateArticle(forms.ModelForm):
    class Meta:
        # what Model are we working from?
        model= models.Article
        # what fields of this Model do we want?
        # date is automatic
        fields= ['title', 'slug', 'body', 'thumb']

djangonautic/articles/views.py
from django.shortcuts import render, redirect
# to make use of the Article model, it must be imported
from .models import Article
# library for sending simple HTTP responses
from django.http import HttpResponse
# decorator for denoting views for which login is required
from django.contrib.auth.decorators import login_required
# importing our forms
from . import forms

# Create your views here.

# view for list of all articles
def article_list(request):
    # grabbing all record of Article database table, ordering by the date field
    articles= Article.objects.all().order_by('date')
    # returning render of a template (Django knows to look in templates folder)
    # parameters for render function are 1. the request object,  2. the template name with relative path from templates directory, and 3. dictionary of data to send to the template (called context)
    return render(request=request, template_name='articles/article_list.html', context={'articles': articles})

# view for a single article with all of its details
# takes in request as first argument and a slug as the second
def article_detail(request, slug):
    # return HttpResponse(slug)
    # want to query the database for an article based on the provided slug
    # we will then use that aricle's information to fill in a template to be returned by this view
    article= Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

# require login and redirect to login page if not logged in
@login_required(login_url='accounts:login')
def article_create(request):
    if request.method == 'POST':
        # files come along on their own FILES field
        # binding data to forms
        form= forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # This save() method accepts an optional commit keyword argument, which accepts either True or False
                # If you call save() with commit=False, then it will return an object that hasn’t yet been saved to the database
                # In this case, it’s up to you to call save() on the resulting model instance.
            instance= form.save(commit=False)
            # want to add current user as author for this instance
            instance.author= request.user
            # finally save instance to database
            instance.save()
            return redirect(to= 'articles:list')
    else:
        form= forms.CreateArticle()

    return render(request= request, template_name= 'articles/article_create.html', context= {'form': form})

djangonautic/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article!</h2>
        <!-- add on encryption typee since we are uploading an image with this form -->
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" name="article_create_form" value="Create">
        </form>
    </div>
    <!-- add in JS script for pre-populating slug field -->
    <script src="/static/slugify.js" type="text/javascript"></script>
{% endblock %}

djangonautic/articles/templates/articles/article_detail.html
<!-- extends the lase layout template -->
{% extends 'base_layout.html'%}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{article.thumb.url}}" alt="Thumbnail image for this article">
        <h2>{{ article.title }}</h2>
        <p> By {{ article.author.username }}</p>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

djangonautic/articles/templates/articles/article_list.html
<!-- this template extends another base template -->
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Article List</h1>
    <div class="articles">
        <!-- template tag utilizing data passed in by View -->
        {% for article in articles%}
            <div class="article">
                <!-- using template tag to get url based on the name parameter assigned when creating the urls -->
                <!-- passing in the aricle slug as the url needs that parameter to link to the correct article -->
                <!-- getting detail url from articles namespace -->
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
                <p class="author">added by {{ article.author.username }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}